# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sozluk.ui'
#
# Created: Wed Feb  3 18:10:37 2016
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(656, 606)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(570, 10, 71, 61))
        self.pushButton.setText(_fromUtf8(""))
        self.pushButton.setIconSize(QtCore.QSize(51, 51))
        self.pushButton.setAutoDefault(False)
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 170, 601, 389))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 0, 1, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.label = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.opacitySlider = QtGui.QSlider(self.gridLayoutWidget_2)
        self.opacitySlider.setMinimum(30)
        self.opacitySlider.setMaximum(100)
        self.opacitySlider.setSingleStep(5)
        self.opacitySlider.setPageStep(5)
        self.opacitySlider.setProperty("value", 100)
        self.opacitySlider.setOrientation(QtCore.Qt.Horizontal)
        self.opacitySlider.setInvertedAppearance(False)
        self.opacitySlider.setInvertedControls(False)
        self.opacitySlider.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.opacitySlider.setObjectName(_fromUtf8("opacitySlider"))
        self.horizontalLayout.addWidget(self.opacitySlider)
        self.gridLayout_2.addLayout(self.horizontalLayout, 2, 1, 1, 1)
        self.relatedList = QtGui.QListWidget(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.relatedList.sizePolicy().hasHeightForWidth())
        self.relatedList.setSizePolicy(sizePolicy)
        self.relatedList.setMinimumSize(QtCore.QSize(258, 330))
        self.relatedList.setMaximumSize(QtCore.QSize(393, 319))
        self.relatedList.setStyleSheet(_fromUtf8("width:10px"))
        self.relatedList.setAutoScroll(False)
        self.relatedList.setAutoScrollMargin(16)
        self.relatedList.setTabKeyNavigation(True)
        self.relatedList.setMovement(QtGui.QListView.Static)
        self.relatedList.setResizeMode(QtGui.QListView.Fixed)
        self.relatedList.setObjectName(_fromUtf8("relatedList"))
        self.gridLayout_2.addWidget(self.relatedList, 1, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.resultsBox = QtGui.QTextBrowser(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resultsBox.sizePolicy().hasHeightForWidth())
        self.resultsBox.setSizePolicy(sizePolicy)
        self.resultsBox.setMinimumSize(QtCore.QSize(0, 0))
        self.resultsBox.setMaximumSize(QtCore.QSize(333, 16777215))
        self.resultsBox.setObjectName(_fromUtf8("resultsBox"))
        self.gridLayout_2.addWidget(self.resultsBox, 1, 1, 1, 1)
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(9, 10, 551, 80))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayoutWidget = QtGui.QWidget(self.frame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(13, 10, 524, 61))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pushButtonTeknikTerimler = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButtonTeknikTerimler.setCheckable(True)
        self.pushButtonTeknikTerimler.setObjectName(_fromUtf8("pushButtonTeknikTerimler"))
        self.gridLayout.addWidget(self.pushButtonTeknikTerimler, 1, 2, 1, 1)
        self.pushButtonTurkceIngilizce = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButtonTurkceIngilizce.setCheckable(True)
        self.pushButtonTurkceIngilizce.setChecked(True)
        self.pushButtonTurkceIngilizce.setObjectName(_fromUtf8("pushButtonTurkceIngilizce"))
        self.gridLayout.addWidget(self.pushButtonTurkceIngilizce, 0, 0, 1, 1)
        self.pushButtonTipTerimleri = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButtonTipTerimleri.setCheckable(True)
        self.pushButtonTipTerimleri.setObjectName(_fromUtf8("pushButtonTipTerimleri"))
        self.gridLayout.addWidget(self.pushButtonTipTerimleri, 0, 3, 1, 1)
        self.pushButtonBilgisayarTerimleri = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButtonBilgisayarTerimleri.setStyleSheet(_fromUtf8(""))
        self.pushButtonBilgisayarTerimleri.setCheckable(True)
        self.pushButtonBilgisayarTerimleri.setObjectName(_fromUtf8("pushButtonBilgisayarTerimleri"))
        self.gridLayout.addWidget(self.pushButtonBilgisayarTerimleri, 1, 1, 1, 1)
        self.pushButtonIngilizceTurkce = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButtonIngilizceTurkce.setCheckable(True)
        self.pushButtonIngilizceTurkce.setObjectName(_fromUtf8("pushButtonIngilizceTurkce"))
        self.gridLayout.addWidget(self.pushButtonIngilizceTurkce, 1, 0, 1, 1)
        self.pushButtonBilisimTerimleri = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButtonBilisimTerimleri.setCheckable(True)
        self.pushButtonBilisimTerimleri.setDefault(False)
        self.pushButtonBilisimTerimleri.setFlat(False)
        self.pushButtonBilisimTerimleri.setObjectName(_fromUtf8("pushButtonBilisimTerimleri"))
        self.gridLayout.addWidget(self.pushButtonBilisimTerimleri, 0, 1, 1, 1)
        self.pushButtonElektronikTerimleri = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButtonElektronikTerimleri.setCheckable(True)
        self.pushButtonElektronikTerimleri.setObjectName(_fromUtf8("pushButtonElektronikTerimleri"))
        self.gridLayout.addWidget(self.pushButtonElektronikTerimleri, 0, 2, 1, 1)
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(10, 94, 551, 61))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.frame_2)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 451, 31))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.searchBox = QtGui.QLineEdit(self.horizontalLayoutWidget_2)
        self.searchBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.searchBox.setWhatsThis(_fromUtf8(""))
        self.searchBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.searchBox.setText(_fromUtf8(""))
        self.searchBox.setDragEnabled(False)
        self.searchBox.setObjectName(_fromUtf8("searchBox"))
        self.horizontalLayout_2.addWidget(self.searchBox)
        self.clearButton = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.clearButton.setObjectName(_fromUtf8("clearButton"))
        self.horizontalLayout_2.addWidget(self.clearButton)
        self.pushButton_3 = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.pushButton_2 = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.findIncludings = QtGui.QCheckBox(self.frame_2)
        self.findIncludings.setGeometry(QtCore.QRect(11, 36, 171, 21))
        self.findIncludings.setChecked(True)
        self.findIncludings.setObjectName(_fromUtf8("findIncludings"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 656, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuMenu = QtGui.QMenu(self.menubar)
        self.menuMenu.setObjectName(_fromUtf8("menuMenu"))
        self.menuG_r_n_m = QtGui.QMenu(self.menuMenu)
        self.menuG_r_n_m.setObjectName(_fromUtf8("menuG_r_n_m"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionWindows = QtGui.QAction(MainWindow)
        self.actionWindows.setObjectName(_fromUtf8("actionWindows"))
        self.actionPlastique = QtGui.QAction(MainWindow)
        self.actionPlastique.setObjectName(_fromUtf8("actionPlastique"))
        self.actionOxygen = QtGui.QAction(MainWindow)
        self.actionOxygen.setObjectName(_fromUtf8("actionOxygen"))
        self.actionCleanlooks = QtGui.QAction(MainWindow)
        self.actionCleanlooks.setObjectName(_fromUtf8("actionCleanlooks"))
        self.actionBespin = QtGui.QAction(MainWindow)
        self.actionBespin.setObjectName(_fromUtf8("actionBespin"))
        self.actionCDE = QtGui.QAction(MainWindow)
        self.actionCDE.setObjectName(_fromUtf8("actionCDE"))
        self.actionGTK = QtGui.QAction(MainWindow)
        self.actionGTK.setObjectName(_fromUtf8("actionGTK"))
        self.actionQtcurve = QtGui.QAction(MainWindow)
        self.actionQtcurve.setObjectName(_fromUtf8("actionQtcurve"))
        self.actionMotif = QtGui.QAction(MainWindow)
        self.actionMotif.setObjectName(_fromUtf8("actionMotif"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionHide = QtGui.QAction(MainWindow)
        self.actionHide.setObjectName(_fromUtf8("actionHide"))
        self.actionShow = QtGui.QAction(MainWindow)
        self.actionShow.setObjectName(_fromUtf8("actionShow"))
        self.menuG_r_n_m.addAction(self.actionWindows)
        self.menuG_r_n_m.addAction(self.actionPlastique)
        self.menuG_r_n_m.addAction(self.actionOxygen)
        self.menuG_r_n_m.addAction(self.actionCleanlooks)
        self.menuG_r_n_m.addAction(self.actionBespin)
        self.menuG_r_n_m.addAction(self.actionCDE)
        self.menuG_r_n_m.addAction(self.actionGTK)
        self.menuG_r_n_m.addAction(self.actionQtcurve)
        self.menuG_r_n_m.addAction(self.actionMotif)
        self.menuMenu.addAction(self.menuG_r_n_m.menuAction())
        self.menuMenu.addAction(self.actionHide)
        self.menuMenu.addAction(self.actionExit)
        self.menuMenu.addAction(self.actionShow)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.clearButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.searchBox.clear)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.closeApplication)
        QtCore.QObject.connect(self.relatedList, QtCore.SIGNAL(_fromUtf8("itemSelectionChanged()")), MainWindow.relatedSelected)
        QtCore.QObject.connect(self.opacitySlider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label.setNum)
        QtCore.QObject.connect(self.pushButton_3, QtCore.SIGNAL(_fromUtf8("clicked()")), self.searchBox.paste)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), self.searchBox.selectAll)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), self.searchBox.copy)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.clearButton, self.pushButton)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_4.setText(_translate("MainWindow", "Anlam", None))
        self.label_2.setText(_translate("MainWindow", "Saydamlık %", None))
        self.label.setText(_translate("MainWindow", "100", None))
        self.label_3.setText(_translate("MainWindow", "Sözcükler", None))
        self.frame.setStatusTip(_translate("MainWindow", "Arama yapılacak kategori", None))
        self.pushButtonTeknikTerimler.setText(_translate("MainWindow", "Teknik Terimler", None))
        self.pushButtonTurkceIngilizce.setText(_translate("MainWindow", "Türkçe->ingilizce", None))
        self.pushButtonTipTerimleri.setText(_translate("MainWindow", "Tıp Terimleri", None))
        self.pushButtonBilgisayarTerimleri.setText(_translate("MainWindow", "Bilgisayar Terimleri", None))
        self.pushButtonIngilizceTurkce.setText(_translate("MainWindow", "İngilizce->Türkçe", None))
        self.pushButtonBilisimTerimleri.setText(_translate("MainWindow", "Bilişim Terimleri", None))
        self.pushButtonElektronikTerimleri.setText(_translate("MainWindow", "Elektronik Terimleri", None))
        self.searchBox.setToolTip(_translate("MainWindow", "Aramanızı buraya yazın, yapıştırın ya da sürükleyip bırakın", None))
        self.searchBox.setStatusTip(_translate("MainWindow", "Aramanızı buraya yazın, yapıştırın ya da sürükleyip bırakın", None))
        self.searchBox.setPlaceholderText(_translate("MainWindow", "Ara", None))
        self.clearButton.setText(_translate("MainWindow", "Temizle", None))
        self.pushButton_3.setText(_translate("MainWindow", "Yapıştır", None))
        self.pushButton_2.setText(_translate("MainWindow", "Kopyala", None))
        self.findIncludings.setText(_translate("MainWindow", "İçinde geçenleri de bul", None))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu", None))
        self.menuG_r_n_m.setTitle(_translate("MainWindow", "Görünüm", None))
        self.actionWindows.setText(_translate("MainWindow", "Windows", None))
        self.actionPlastique.setText(_translate("MainWindow", "Plastique", None))
        self.actionOxygen.setText(_translate("MainWindow", "Oxygen", None))
        self.actionCleanlooks.setText(_translate("MainWindow", "Cleanlooks", None))
        self.actionBespin.setText(_translate("MainWindow", "Bespin", None))
        self.actionCDE.setText(_translate("MainWindow", "CDE", None))
        self.actionGTK.setText(_translate("MainWindow", "GTK", None))
        self.actionQtcurve.setText(_translate("MainWindow", "Qtcurve", None))
        self.actionMotif.setText(_translate("MainWindow", "Motif", None))
        self.actionExit.setText(_translate("MainWindow", "Çıkış", None))
        self.actionHide.setText(_translate("MainWindow", "Gizle", None))
        self.actionShow.setText(_translate("MainWindow", "Göster", None))

